# Generated by Django 4.0.5 on 2022-07-27 06:28

from django.db import migrations, models
import jommerce.auth.models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0002_session_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="expire_date",
            field=models.DateTimeField(
                blank=True,
                default=jommerce.auth.models.get_default_expire_date,
                verbose_name="expire_date",
            ),
        ),
    ]
