# Generated by Django 4.0.5 on 2022-07-11 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0002_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'active'), (1, 'inactive')], default=0, verbose_name='status'),
        ),
    ]
