# Generated by Django 4.0.5 on 2022-07-22 03:40

from django.db import migrations, models
import djplus.auth.models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0004_alter_session_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='id',
            field=models.CharField(default=djplus.auth.models.generate_session_id, max_length=32, primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
