# Generated by Django 4.0.5 on 2022-07-22 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0005_alter_session_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='status',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
