# Generated by Django 4.0.5 on 2022-07-22 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0006_remove_user_status_remove_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='expire_date',
        ),
        migrations.RemoveField(
            model_name='session',
            name='ip',
        ),
    ]
